#!/bin/bash

# execute this script once to initially set up influxdb and grafana

export sh_basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

. ${sh_basedir}/.env
export INFLUX_TOKEN="$INFLUX_TOKEN"

SECRET_FILE="${sh_basedir}/data/secrets/.env"

echo "creating buckets and tokens"

# create influx buckets; bucket "smarthome" is already created by docker-setup
docker exec sh-influxdb influx bucket create --org "$INFLUX_ORG" --name "$INFLUX_DERIVED_BUCKET"   --retention "$INFLUX_DERIVED_RETENTION" > /dev/null
docker exec sh-influxdb influx bucket create --org "$INFLUX_ORG" --name "$INFLUX_LONGRANGE_BUCKET" --retention "$INFLUX_LONGRANGE_RETENTION" > /dev/null

# create access tokens for the influx buckets
id_bucket=$(docker exec sh-influxdb influx bucket list --org "$INFLUX_ORG"           | awk -v bucket="$INFLUX_BUCKET"           '($2 == bucket){print $1}')
id_derived_bucket=$(docker exec sh-influxdb influx bucket list --org "$INFLUX_ORG"   | awk -v bucket="$INFLUX_DERIVED_BUCKET"   '($2 == bucket){print $1}')
id_longrange_bucket=$(docker exec sh-influxdb influx bucket list --org "$INFLUX_ORG" | awk -v bucket="$INFLUX_LONGRANGE_BUCKET" '($2 == bucket){print $1}')

INFLUX_SMARTHOME_TOKEN=$(docker exec sh-influxdb influx auth create --org "$INFLUX_ORG" --write-bucket "$id_bucket" | awk 'NR==2 {print $2}')
INFLUX_LONGRANGE_TOKEN=$(docker exec sh-influxdb influx auth create --org "$INFLUX_ORG" --write-bucket "$id_longrange_bucket" | awk 'NR==2 {print $2}')
INFLUX_READALL_TOKEN=$(docker exec sh-influxdb influx auth create --org "$INFLUX_ORG" --read-buckets | awk 'NR==2 {print $2}')

echo "adding new generated tokens to the end of your .env file."
echo "# generated by config/Setup-once.sh" > $SECRET_FILE
echo "export INFLUX_SMARTHOME_TOKEN=${INFLUX_SMARTHOME_TOKEN}" >> $SECRET_FILE
echo "export INFLUX_LONGRANGE_TOKEN=${INFLUX_LONGRANGE_TOKEN}" >> $SECRET_FILE
echo "export INFLUX_READALL_TOKEN=${INFLUX_READALL_TOKEN}" >> $SECRET_FILE

echo "imorting tasks"
for task in ${sh_basedir}/influxdb/tasks/*.json; do
  echo "importing task $task"
  taskfile="$(basename $task)"
  docker cp "$task" sh-influxdb:/tmp/"$taskfile"
  docker exec -it sh-influxdb influx apply --org "$INFLUX_ORG" -f /tmp/"$taskfile" --force yes
done

echo "creating datasource in grafana"

cat $sh_basedir/grafana/datasource.json \
| sed -e "s/%%INFLUX_ORG%%/${INFLUX_ORG}/" \
| sed -e "s/%%INFLUX_BUCKET%%/${INFLUX_BUCKET}/" \
| sed -e "s/%%INFLUX_READALL_TOKEN%%/${INFLUX_READALL_TOKEN}/" \
> /tmp/datasource.json

DATASOURCE_ID=$(curl -s -X POST http://localhost:3000/api/datasources -u "admin":"admin" -H "Content-Type: application/json" -d @/tmp/datasource.json )
echo $DATASOURCE_ID

export DATASOURCE_ID=$(echo $DATASOURCE_ID | python3 -c "import sys, json; print(json.load(sys.stdin)['datasource']['uid'])" )

echo "importing dashboards to grafana"
for dashboard in ${sh_basedir}/grafana/dashboards/*.json; do
  echo "importing dashboard $dashboard"
  cat "$dashboard" \
  | python3 "${sh_basedir}/grafana/transform-dashboard.py" \
  | curl -s -X POST http://localhost:3000/api/dashboards/db -u admin:admin -H "Content-Type: application/json" -d @-
done
