{
 "title": "Climate",
 "time": { "from": "now-3d", "to": "now" },
 "panels": [
  {
   "title": "Inhouse temperatures",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r.domain == \"temperature\" and exists r._value and r.room != \"Terasse\" and r.room != \"outside\")\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: last,\r\n       createEmpty: false\r\n     )\r\n  |> drop(columns:[\"_field\",\"domain\", \"_measurement\",\"device\"])"
    }
   ]
  },
  {
   "title": "Inhouse temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.domain == \"temperature\" and r.room != \"Terasse\" and r.room != \"outside\" and exists r._value )\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: mean,\r\n       createEmpty: false\r\n     )\r\n  |> drop(columns: [\"_measurement\",\"_field\",\"domain\", \"device\"])"
    }
   ]
  },
  {
   "title": "Inhouse mean temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.domain == \"temperature\" and r.room != \"Terasse\" and r.room != \"outside\" and exists r._value )\r\n  |> aggregateWindow(\r\n       every: 10m,\r\n       fn: mean,\r\n       createEmpty: false\r\n     )"
    }
   ]
  },
  {
   "title": "outside temperatures",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r.domain == \"temperature\" and exists r._value and (r.room == \"Terasse\" or r.room == \"outside\"))\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: last,\r\n       createEmpty: false\r\n     )"
    }
   ]
  },
  {
   "title": "outside temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.domain == \"temperature\" and (r.room == \"Terasse\" or r.room == \"outside\") and exists r._value )\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: mean,\r\n       createEmpty: false\r\n     )"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.domain == \"humidity\")\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: mean,\r\n       createEmpty: false\r\n     )"
    }
   ]
  },
  {
   "title": "pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"remoteweather\" and r._field == \"pressure\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "windspeed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"remoteweather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"windspeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}