{
 "title": "Energy daily",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "daily energy",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthomederived\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"daily_energy\")\r\n  |> filter(fn: (r) =>\r\n      r._field == \"swm_used\" or\r\n      r._field == \"green_used\" or\r\n      r._field == \"green_upstream\"\r\n  )\r\n\r\n"
    }
   ]
  },
  {
   "title": "upstream ratio",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthomederived\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"daily_energy\")\r\n  |> filter(fn: (r) =>\r\n      r._field == \"green_upstream\" or\r\n      r._field == \"green_injected\"\r\n  )\r\n  |> pivot(\r\n      rowKey: [\"_time\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"upstream_ratio\",\r\n      _value: -1.0 * r.green_upstream / r.green_injected\r\n  }))\r\n\r\n"
    }
   ]
  },
  {
   "title": "total efficiency",
   "type": "barchart",
   "description": "inhouse used energy divided by solar input",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthomederived\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily_energy\" and\r\n    (\r\n      r._field == \"solarInputPower\" or\r\n      r._field == \"outputHomePower\" or\r\n      r._field == \"gridInputPower\" or\r\n      r._field == \"green_upstream\"\r\n    )\r\n  )\r\n  |> pivot(\r\n      rowKey: [\"_time\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"solar_efficiency\",\r\n      _field: \"eta\",\r\n      _value: (r.outputHomePower + r.green_upstream - r.gridInputPower) / r.solarInputPower\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "buffering efficiency",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthomederived\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"daily_energy\" and \r\n    (r._field == \"packInputPower\" or r._field == \"outputPackPower\" or r._field == \"pv_excess\")\r\n  )\r\n  |> pivot(\r\n    rowKey: [\"_time\"],\r\n    columnKey: [\"_field\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with \r\n    _value: r.outputPackPower - r.packInputPower\r\n  }))\r\n  |> drop(columns: [\"outputPackPower\", \"packInputPower\"])"
    }
   ]
  },
  {
   "title": "Energy flows",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthomederived\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"daily_energy\" and (r._field == \"solarInputPower\" or r._field == \"outputPackPower\" or r._field == \"packInputPower\" or r._field == \"gridInputPower\" or r._field == \"outputHomePower\" ))\r\n|> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  }
 ]
}