{
 "title": "Misc",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => \r\n       (r._measurement == \"zendure\" and (r._field == \"solarInputPower\" or r._field == \"outputHomePower\"))\r\n    or (r._measurement == \"tasmota\" and r._field == \"downstream\")\r\n)\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => \r\n       (r._measurement == \"zendure\" and (r._field == \"solarInputPower\" or r._field == \"outputHomePower\"))\r\n    or (r._measurement == \"tasmota\" and r._field == \"downstream\")\r\n)\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n|> fill(usePrevious: true)\r\n|> group()\r\n|> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n|> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: if r.solarInputPower > (r.outputHomePower + r.downstream)\r\n        then r.solarInputPower - (r.outputHomePower + r.downstream)\r\n        else 0.0,\r\n    _field: \"PV_Ueberschuss\"\r\n}))"
    }
   ]
  },
  {
   "title": "heartbeats",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\nsensors =\r\n  array.from(rows: [\r\n    {_measurement: \"fritz\", _value: 0},\r\n    {_measurement: \"mystrom\", _value: 0},\r\n    {_measurement: \"remoteweather\", _value: 0},\r\n    {_measurement: \"smart-manager\", _value: 0},\r\n    {_measurement: \"smarthings\", _value: 0},\r\n    {_measurement: \"tasmota\", _value: 0},\r\n    {_measurement: \"zendure\", _value: 0}\r\n  ])\r\n\r\ndata =\r\n  from(bucket: \"smarthome\")\r\n    |> range(start: -6m)\r\n    |> filter(fn: (r) => r.domain == \"heartbeat\")\r\n    |> group(columns: [\"_measurement\"])\r\n    |> count()\r\n    |> map(fn: (r) => ({\r\n        _measurement: r._measurement,\r\n        _value: if r._value > 0 then 1 else 0\r\n    }))\r\n\r\nunion(tables: [sensors, data])\r\n  |> group(columns: [\"_measurement\"])\r\n  |> max()"
    }
   ]
  },
  {
   "title": "Presence signals",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"fritz\" and r.domain == \"presence\")\r\n|> drop(columns:[\"domain\",\"_measurement\"])\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.domain == \"network\" and exists r._value )\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: max,\r\n       createEmpty: false\r\n     )\r\n  |> drop(columns: [\"_measurement\",\"domain\"])"
    }
   ]
  }
 ]
}