{
 "title": "Presence",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "presence",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.domain == \"presence\" and (\r\n    r._field == \"Angela\" or\r\n    r._field == \"Georg\" or\r\n    r._field == \"Bekki\" or\r\n    r._field == \"Tristan\" or\r\n    r._field == \"Jonathan\" or \r\n    r._field == \"Aylin\" or\r\n    r._field == \"Emanuel\" or\r\n    r._field == \"Carina\" or\r\n    r._field == \"Johannes\"\r\n))\r\n|> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Inhouse temperatures",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r.domain == \"temperature\" and exists r._value and r.room != \"Terasse\" and r.room != \"outside\")\r\n  |> aggregateWindow(\r\n       every: v.windowPeriod,\r\n       fn: last,\r\n       createEmpty: false\r\n     )\r\n  |> drop(columns:[\"_field\",\"domain\", \"_measurement\",\"device\"])"
    }
   ]
  },
  {
   "title": "crowd",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"fritz\" and r.domain == \"presence\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.domain == \"humidity\" and ( r.room == \"-1 Many\" or r.room == \"1 Bad\" or r.room == \"2 Bad\"))\r\n|> drop(columns: [\"domain\"])\r\n|> last()"
    }
   ]
  }
 ]
}