{
 "title": "Sun Prediction",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "generosity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"smarthome\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._field == \"generosity2\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "sun prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._field == \"sunpredict\" and (r.dimension == \"cc_by_sd\" or r.dimension == \"sunshine_duration\") )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "solar panels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"zendure\")\r\n  |> filter(fn: (r) =>\r\n    r._field == \"solarPower1\" or\r\n    r._field == \"solarPower2\" or\r\n    r._field == \"solarPower3\" or\r\n    r._field == \"solarPower4\"\r\n  )\r\n  |> drop(columns: [\"domain\", \"electric\", \"room\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "battery level",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"smarthome\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => (r._measurement == \"zendure\" and r._field == \"electricLevel\"))\r\n  |> drop(columns: [\"domain\", \"electric\", \"room\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Solar Power",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"smarthomederived\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"daily_energy\" and r._field == \"solarInputPower\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  }
 ]
}