QUERY_INTERVAL = 60
DYNAMIC_CONFIG_PATH = '/cproj/Home-IT/smarthome/PV-PARAMETER.md'

MQTT_USERNAME = 'mqtt-username'
MQTT_PASSWORD = 'mqtt-password'

[smartmanager]
SMART_MANAGER_INTERVAL = 90
SMART_MANAGER_DATADIR = '/app/sensors'
INJECTION_MAX = 800
BASELOAD = 97
BATT_MIN = 10
BATT_MAX = 99
BATT_CAPACITY = 4000

# if you wanna set green injection to a fixed value
#HARDOUTPUT = 100

[mqtt]
broker   = 'mqtt'
port     = 1883
topic    = 'tele/+/SENSOR'

# --- Fritzbox ---
[fritz]
query_interval = 300
devicemap = '/cproj/Home-IT/smarthome/device-map.json'

[fritzdevices]
devices = [
    { host = 'fritz.box', user = 'username', password = 'password', features = 'hosts transmission_rate ha' },
]
