name: Container Retention 

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  #schedule:
  #  - cron: "0 1 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete old container versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: smarthome-sensors
          package-type: container
          min-versions-to-keep: 7
          delete-only-untagged-versions: false