name: Container Retention 

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  delete-package-versions:
    name: Delete old packages
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.PAT }}
          image-names: "smarthome-sensors*"  # smarthome-sensor packages owned by the account
          tag-selection: untagged
          cut-off: 7d
